/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 23-May-2023 11:36:29
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 7;
const real64_T NUM[7] = {
  8.416965284919e-05,-0.0003073293531054,0.0003621498988963,                 0,
  -0.0003621498988963,0.0003073293531054,-8.416965284919e-05
};
const int DL = 7;
const real64_T DEN[7] = {
                   1,    -5.91735845754,    14.59421657716,   -19.20299178142,
      14.21727066496,   -5.615639850186,   0.9245028496715
};
