/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 23-May-2023 10:43:23
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
  9.956434598171e-05,-0.0003977119596859,0.0005962956011508,-0.0003977119596859,
  9.956434598171e-05
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.988527438489,    5.965648080101,   -3.965713623754,
     0.9885929825153
};
