/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 23-May-2023 11:38:03
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 9
 * Denominator Length  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 9;
const real64_T NUM[9] = {
  0.0001386148603066,-0.0008941363041786, 0.002645441952704,-0.004752341760764,
   0.005724842507282,-0.004752341760764, 0.002645441952704,-0.0008941363041786,
  0.0001386148603066
};
const int DL = 9;
const real64_T DEN[9] = {
                   1,    -7.72321863505,    26.15140222984,   -50.70729295573,
      61.58018767821,   -47.96303158011,    23.39747234073,   -6.536018127949,
     0.8004990842548
};
