/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 23-May-2023 11:17:27
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 13
 * Denominator Length  : 13
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 13;
const real64_T NUM[13] = {
  0.0001132318145315,-0.001188744707907,  0.00583418747083, -0.01774229188121,
    0.03731807232746, -0.05729638817713,  0.06592386630908, -0.05729638817713,
    0.03731807232746, -0.01774229188121,  0.00583418747083,-0.001188744707907,
  0.0001132318145315
};
const int DL = 13;
const real64_T DEN[13] = {
                   1,   -11.25788097388,    58.39760060551,   -184.5515034372,
       395.720145247,    -606.490284968,    681.2466447821,   -565.0754465728,
      343.5216687085,   -149.2686525549,    44.00821125963,   -7.904726818107,
     0.6542247445185
};
