/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 23-May-2023 11:29:17
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 7;
const real64_T NUM[7] = {
   3.53018854343e-05,-0.0001386267334485,0.0001713478153857,                 0,
  -0.0001713478153857,0.0001386267334485,-3.53018854343e-05
};
const int DL = 7;
const real64_T DEN[7] = {
                   1,   -5.964267770369,    14.82307054653,    -19.6495728049,
      14.65297347774,   -5.828171870203,   0.9659684212516
};
